import type { ActivityItem } from "../types/activity";
import type { Project } from "../types/project";

export type SelectedCommit = ActivityItem & {
  commitHash: string;
};

export type PrPackageInput = {
  project: Project;
  commits: ActivityItem[];
  baseBranch: string;
  branchName: string;
  title: string;
  notes?: string;
};

export type PrPackage = {
  selectedCommits: SelectedCommit[];
  commandText: string;
  prBody: string;
  warnings: string[];
  remoteUrl?: string | null;
};

export function generatePrPackage(input: PrPackageInput): PrPackage {
  const selectedCommits = input.commits.filter(hasCommitHash);
  const warnings = createWarnings(input, selectedCommits);
  const orderedCommits = [...selectedCommits].sort(
    (a, b) => new Date(a.occurredAt).getTime() - new Date(b.occurredAt).getTime(),
  );

  const commandLines = [
    `git checkout ${input.baseBranch}`,
    "git pull",
    `git checkout -b ${input.branchName}`,
    ...orderedCommits.map((commit) => `git cherry-pick ${commit.commitHash}`),
  ];

  return {
    selectedCommits,
    commandText: commandLines.join("\n"),
    prBody: createPrBody(input, orderedCommits),
    warnings,
    remoteUrl: input.project.githubUrl,
  };
}

export function suggestedBaseBranch(commits: ActivityItem[]) {
  return (
    commits.flatMap((commit) => commit.refs ?? []).find((ref) => ref.isCurrent)?.name ??
    commits.flatMap((commit) => commit.refs ?? []).find((ref) => ref.kind === "local")?.name ??
    commits.find((commit) => commit.branch)?.branch ??
    "main"
  );
}

export function suggestedPrTitle(commits: ActivityItem[], projectName: string) {
  const firstSubject = commits[0]?.summary.split("\n")[0]?.trim();
  return firstSubject ? firstSubject : `${projectName} updates`;
}

export function suggestedBranchName(projectName: string, commits: ActivityItem[]) {
  const subject = commits[0]?.summary.split("\n")[0] ?? "updates";
  const slug = slugify(`${projectName}-${subject}`).slice(0, 64);
  return `worktrace/${slug || "selected-commits"}`;
}

export function fullPrPackageText(pkg: PrPackage, title: string) {
  const parts = [
    `PR Title:\n${title}`,
    `\nCommands:\n${pkg.commandText}`,
    `\nPR Body:\n${pkg.prBody}`,
  ];

  if (pkg.remoteUrl) {
    parts.push(`\nRemote:\n${pkg.remoteUrl}`);
  } else {
    parts.push("\nRemote:\nremote PR URL unavailable");
  }

  if (pkg.warnings.length) {
    parts.push(`\nWarnings:\n${pkg.warnings.map((warning) => `- ${warning}`).join("\n")}`);
  }

  return parts.join("\n");
}

function createWarnings(input: PrPackageInput, selectedCommits: SelectedCommit[]) {
  const warnings: string[] = [];
  const missingHashes = input.commits.length - selectedCommits.length;
  const branchSets = selectedCommits.map((commit) => containingRefNames(commit));
  const sharedBranches = branchSets.length
    ? branchSets.reduce((shared, refs) => new Set([...shared].filter((ref) => refs.has(ref))))
    : new Set<string>();

  if (input.commits.length === 0) {
    warnings.push("Select at least one commit before building a PR package.");
  }
  if (!input.baseBranch.trim()) {
    warnings.push("Select a base branch before copying a PR package.");
  }
  if (missingHashes > 0) {
    warnings.push(`${missingHashes} selected item(s) do not have commit hashes and were excluded.`);
  }
  if (
    input.baseBranch.trim() &&
    selectedCommits.some((commit) => !containingRefNames(commit).has(input.baseBranch.trim()))
  ) {
    warnings.push("Some selected commits are not reachable from the selected base branch.");
  }
  if (selectedCommits.length > 1 && sharedBranches.size === 0) {
    warnings.push("Selected commits do not share a known branch ref.");
  }
  if (!input.project.repoPath) {
    warnings.push("This project has no local repository path configured.");
  }
  if (!input.project.githubUrl) {
    warnings.push("This project has no GitHub URL configured; GitHub PR creation will try the origin remote.");
  }

  return warnings;
}

function containingRefNames(commit: ActivityItem) {
  const names = new Set((commit.refs ?? []).map((ref) => ref.name));
  if (commit.branch) {
    names.add(commit.branch);
  }
  return names;
}

function createPrBody(input: PrPackageInput, orderedCommits: SelectedCommit[]) {
  const notes = input.notes?.trim();
  const commitLines = orderedCommits.map((commit) => {
    const subject = commit.summary.split("\n")[0].trim();
    return `- ${shortHash(commit.commitHash)} ${subject}`;
  });

  return [
    "## Summary",
    notes || `Prepared from ${orderedCommits.length} selected WorkTrace commit(s) for ${input.project.name}.`,
    "",
    "## Selected Commits",
    commitLines.length ? commitLines.join("\n") : "- No valid commit hashes selected.",
    "",
    "## Test Checklist",
    "- [ ] Build passes",
    "- [ ] Relevant tests pass",
    "- [ ] Manual review complete",
    "",
    "_Generated by WorkTrace PR Builder._",
  ].join("\n");
}

function hasCommitHash(commit: ActivityItem): commit is SelectedCommit {
  return Boolean(commit.commitHash?.trim());
}

function shortHash(hash: string) {
  return hash.slice(0, 8);
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}
