pub mod activity;
pub mod activity_groups;
pub mod app_updates;
pub mod calendar;
pub mod daily_plan;
pub mod dashboard;
pub mod embeddings;
pub mod focus_sessions;
pub mod friction;
pub mod git_sync;
pub mod github;
pub mod manual_logs;
pub mod manual_log_attachments;
pub mod nudges;
pub mod priority_reminders;
pub mod project_stats;
pub mod projects;
pub mod reports;
pub mod settings;
pub mod sparc_force;
pub mod task_attachments;
pub mod voice;
pub mod weekly_tasks;
pub mod windows;
pub mod workspaces;

pub fn handlers() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        projects::list_projects,
        projects::create_project,
        projects::update_project,
        projects::archive_project,
        projects::validate_repo_path,
        projects::list_git_branches,
        projects::list_git_refs,
        projects::list_git_worktrees,
        projects::get_project_git_focus,
        projects::save_project_git_focus,
        project_stats::get_project_stats,
        project_stats::get_category_distribution,
        project_stats::get_recent_commits,
        project_stats::get_top_contributors,
        dashboard::get_dashboard_stats,
        dashboard::get_weekly_activity_hours,
        dashboard::get_project_breakdown,
        daily_plan::get_daily_plan,
        daily_plan::upsert_daily_plan,
        daily_plan::replace_daily_plan_items,
        daily_plan::update_daily_plan_item,
        daily_plan::get_today_command_center,
        embeddings::get_embedding_status,
        embeddings::test_embedding_provider,
        embeddings::connect_embedding_provider,
        embeddings::disconnect_embedding_provider,
        embeddings::refresh_activity_embeddings,
        embeddings::queue_activity_embedding_refresh,
        embeddings::get_background_job_status,
        embeddings::run_background_jobs_once,
        embeddings::semantic_activity_search,
        activity::list_activity,
        activity_groups::list_activity_groups,
        activity_groups::suggest_activity_groups,
        activity_groups::preview_activity_group_suggestions,
        activity_groups::refresh_activity_group_suggestions,
        activity_groups::create_activity_group,
        activity_groups::update_activity_group,
        activity_groups::delete_activity_group,
        activity_groups::replace_activity_group_items,
        activity_groups::list_grouping_evidence,
        activity_groups::merge_activity_groups,
        activity_groups::split_activity_group,
        activity_groups::move_activity_group_item,
        activity_groups::lock_activity_group,
        activity_groups::reset_activity_group,
        activity_groups::preview_activity_group_title,
        activity_groups::regenerate_activity_group_title,
        activity_groups::select_activity_group_title_candidate,
        activity_groups::record_activity_group_title_feedback,
        app_updates::get_app_version,
        app_updates::get_release_notes,
        app_updates::check_for_app_update,
        app_updates::install_app_update,
        activity::get_activity_heatmap,
        activity::get_week_summary,
        activity::get_key_highlights,
        calendar::list_calendar_sources,
        calendar::connect_google_calendar,
        calendar::disconnect_calendar_source,
        calendar::set_calendar_source_enabled,
        calendar::sync_calendar_events,
        calendar::list_calendar_events,
        calendar::get_week_capacity,
        focus_sessions::get_active_focus_session,
        focus_sessions::list_focus_sessions,
        focus_sessions::start_focus_session,
        focus_sessions::stop_focus_session,
        focus_sessions::cancel_focus_session,
        friction::get_friction_insights,
        git_sync::sync_commits,
        github::start_github_device_auth,
        github::complete_github_device_auth,
        github::connect_github_pat,
        github::get_github_integration_status,
        github::list_github_accounts,
        github::test_github_account,
        github::test_github_connection,
        github::disconnect_github_account,
        github::disconnect_github,
        github::detect_project_github_binding,
        github::sync_github_project_activity,
        github::create_github_pull_request,
        manual_logs::list_manual_logs,
        manual_logs::create_manual_log,
        manual_logs::quick_capture_log,
        manual_logs::update_manual_log,
        manual_logs::delete_manual_log,
        manual_log_attachments::list_manual_log_attachments,
        manual_log_attachments::add_manual_log_attachment,
        manual_log_attachments::delete_manual_log_attachment,
        manual_log_attachments::open_manual_log_attachment,
        manual_log_attachments::get_manual_log_attachment_preview,
        nudges::list_nudge_dismissals,
        nudges::dismiss_nudge,
        priority_reminders::list_priority_reminders,
        priority_reminders::run_priority_reminder_check,
        priority_reminders::snooze_priority_reminder,
        priority_reminders::dismiss_priority_reminder,
        reports::generate_report,
        reports::save_report,
        reports::list_reports,
        reports::get_report,
        reports::list_report_notes,
        reports::save_daily_review_note,
        reports::get_report_ai_status,
        reports::connect_report_ai_provider,
        reports::test_report_ai_provider,
        reports::disconnect_report_ai_provider,
        reports::list_report_ai_provider_models,
        reports::polish_report,
        reports::cancel_report_ai_stream,
        reports::analyze_report_readiness,
        settings::get_settings,
        settings::update_settings,
        settings::activate_sparc_force_addon,
        settings::validate_backup_location,
        settings::export_settings,
        settings::export_settings_to_file,
        settings::import_settings,
        sparc_force::get_sparc_force_integration_status,
        sparc_force::connect_sparc_force,
        sparc_force::verify_sparc_force_login_otp,
        sparc_force::test_sparc_force_connection,
        sparc_force::sync_sparc_force,
        sparc_force::list_sparc_force_imported_data,
        sparc_force::list_sparc_force_records,
        sparc_force::get_sparc_force_case_detail,
        sparc_force::import_sparc_force_task_to_weekly_task,
        sparc_force::disconnect_sparc_force,
        task_attachments::list_task_attachments,
        task_attachments::add_task_attachment,
        task_attachments::delete_task_attachment,
        task_attachments::open_task_attachment,
        task_attachments::get_task_attachment_preview,
        voice::transcribe_voice_command,
        weekly_tasks::list_weekly_tasks,
        weekly_tasks::create_weekly_task,
        weekly_tasks::update_weekly_task,
        weekly_tasks::delete_weekly_task,
        windows::show_todo_widget,
        windows::hide_todo_widget,
        windows::toggle_todo_widget,
        windows::set_todo_widget_always_on_top,
        windows::show_quick_capture,
        windows::hide_quick_capture,
        windows::toggle_quick_capture,
        windows::get_quick_capture_status,
        windows::configure_quick_capture_shortcut,
        windows::get_desktop_lifecycle_status,
        windows::configure_desktop_lifecycle,
        windows::show_main_window,
        windows::hide_main_window_to_tray,
        windows::quit_app,
        windows::request_tray_sync,
        workspaces::list_workspaces,
        workspaces::create_workspace,
        workspaces::update_workspace,
        workspaces::archive_workspace,
        workspaces::scan_workspace,
        workspaces::import_workspace_repositories,
        workspaces::ignore_workspace_repository,
        workspaces::unignore_workspace_repository
    ]
}
