use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Settings {
    pub name: String,
    pub email: String,
    pub use_gravatar_profile_image: bool,
    pub default_manager_name: String,
    pub git_author_email: String,
    pub default_report_template: String,
    pub working_days: Vec<String>,
    pub daily_work_minutes: i32,
    pub theme: String,
    pub backup_enabled: bool,
    pub backup_schedule: String,
    pub backup_time: String,
    pub backup_day: String,
    pub backup_storage_mode: String,
    pub backup_storage_location: String,
    pub online_backup_status: String,
    pub online_backup_provider: String,
    pub github_connected: bool,
    pub github_username: String,
    pub github_connected_at: String,
    pub github_last_validated_at: String,
    pub announcements_enabled: bool,
    pub announcement_volume: f32,
    pub announcement_voice: String,
    pub announce_focus_events: bool,
    pub announce_nudges: bool,
    pub announce_sync_results: bool,
    pub announce_task_changes: bool,
    pub voice_commands_enabled: bool,
    pub voice_command_mode: String,
    pub voice_command_confirm_before_action: bool,
    pub voice_transcription_provider: String,
    pub voice_online_allowed: bool,
    pub voice_privacy_acknowledged: bool,
    pub voice_groq_model: String,
    pub voice_openrouter_model: String,
    pub report_ai_enabled: bool,
    pub report_ai_provider: String,
    pub report_ai_online_allowed: bool,
    pub report_ai_privacy_acknowledged: bool,
    pub report_ai_local_model_path: String,
    pub report_ai_groq_model: String,
    pub report_ai_nvidia_model: String,
    pub sparc_force_addon_enabled: bool,
    pub onboarding_completed: bool,
    pub onboarding_dismissed_welcome: bool,
    pub onboarding_dismissed_checklist: bool,
    pub onboarding_completed_steps: Vec<String>,
    pub onboarding_completed_at: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BackupLocationValidation {
    pub status: String,
    pub message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SettingsExport {
    pub app: String,
    pub version: u32,
    pub exported_at: String,
    pub settings: Settings,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SettingsImportResult {
    pub settings: Settings,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateSettingsInput {
    pub name: Option<String>,
    pub email: Option<String>,
    pub use_gravatar_profile_image: Option<bool>,
    pub default_manager_name: Option<String>,
    pub git_author_email: Option<String>,
    pub default_report_template: Option<String>,
    pub working_days: Option<Vec<String>>,
    pub daily_work_minutes: Option<i32>,
    pub theme: Option<String>,
    pub backup_enabled: Option<bool>,
    pub backup_schedule: Option<String>,
    pub backup_time: Option<String>,
    pub backup_day: Option<String>,
    pub backup_storage_mode: Option<String>,
    pub backup_storage_location: Option<String>,
    pub online_backup_status: Option<String>,
    pub online_backup_provider: Option<String>,
    pub github_connected: Option<bool>,
    pub github_username: Option<String>,
    pub github_connected_at: Option<String>,
    pub github_last_validated_at: Option<String>,
    pub announcements_enabled: Option<bool>,
    pub announcement_volume: Option<f32>,
    pub announcement_voice: Option<String>,
    pub announce_focus_events: Option<bool>,
    pub announce_nudges: Option<bool>,
    pub announce_sync_results: Option<bool>,
    pub announce_task_changes: Option<bool>,
    pub voice_commands_enabled: Option<bool>,
    pub voice_command_mode: Option<String>,
    pub voice_command_confirm_before_action: Option<bool>,
    pub voice_transcription_provider: Option<String>,
    pub voice_online_allowed: Option<bool>,
    pub voice_privacy_acknowledged: Option<bool>,
    pub voice_groq_model: Option<String>,
    pub voice_openrouter_model: Option<String>,
    pub report_ai_enabled: Option<bool>,
    pub report_ai_provider: Option<String>,
    pub report_ai_online_allowed: Option<bool>,
    pub report_ai_privacy_acknowledged: Option<bool>,
    pub report_ai_local_model_path: Option<String>,
    pub report_ai_groq_model: Option<String>,
    pub report_ai_nvidia_model: Option<String>,
    pub sparc_force_addon_enabled: Option<bool>,
    pub onboarding_completed: Option<bool>,
    pub onboarding_dismissed_welcome: Option<bool>,
    pub onboarding_dismissed_checklist: Option<bool>,
    pub onboarding_completed_steps: Option<Vec<String>>,
    pub onboarding_completed_at: Option<String>,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            name: "John Developer".to_string(),
            email: "johndev@worktrace.app".to_string(),
            use_gravatar_profile_image: false,
            default_manager_name: String::new(),
            git_author_email: String::new(),
            default_report_template: "professional_weekly_summary".to_string(),
            working_days: vec![
                "monday".to_string(),
                "tuesday".to_string(),
                "wednesday".to_string(),
                "thursday".to_string(),
                "friday".to_string(),
            ],
            daily_work_minutes: 480,
            theme: "dark".to_string(),
            backup_enabled: false,
            backup_schedule: "daily".to_string(),
            backup_time: "17:00".to_string(),
            backup_day: "friday".to_string(),
            backup_storage_mode: "local".to_string(),
            backup_storage_location: String::new(),
            online_backup_status: "research".to_string(),
            online_backup_provider: String::new(),
            github_connected: false,
            github_username: String::new(),
            github_connected_at: String::new(),
            github_last_validated_at: String::new(),
            announcements_enabled: true,
            announcement_volume: 0.8,
            announcement_voice: String::new(),
            announce_focus_events: true,
            announce_nudges: true,
            announce_sync_results: true,
            announce_task_changes: true,
            voice_commands_enabled: true,
            voice_command_mode: "push_to_talk".to_string(),
            voice_command_confirm_before_action: true,
            voice_transcription_provider: "local_whisper".to_string(),
            voice_online_allowed: false,
            voice_privacy_acknowledged: false,
            voice_groq_model: "whisper-large-v3-turbo".to_string(),
            voice_openrouter_model: "openai/whisper-1".to_string(),
            report_ai_enabled: true,
            report_ai_provider: "local_llama_cpp".to_string(),
            report_ai_online_allowed: false,
            report_ai_privacy_acknowledged: false,
            report_ai_local_model_path: String::new(),
            report_ai_groq_model: "llama-3.1-8b-instant".to_string(),
            report_ai_nvidia_model: "meta/llama-3.1-70b-instruct".to_string(),
            sparc_force_addon_enabled: false,
            onboarding_completed: false,
            onboarding_dismissed_welcome: false,
            onboarding_dismissed_checklist: false,
            onboarding_completed_steps: Vec::new(),
            onboarding_completed_at: String::new(),
        }
    }
}
